"""Output formatters for different file formats."""

from pathlib import Path
from typing import Dict, List
from datetime import datetime
from rich.console import Console

console = Console()


class BaseFormatter:
    """Base class for formatters."""
    
    def __init__(self, config):
        """Initialize formatter with configuration."""
        self.config = config
    
    def format(self, learning_path: Dict, modules_content: List[Dict], output_path: Path):
        """Format and save content."""
        raise NotImplementedError


class HTMLFormatter(BaseFormatter):
    """Format content as HTML."""
    
    def format(self, learning_path: Dict, modules_content: List[Dict], output_path: Path):
        """Generate HTML output."""
        console.print("[cyan]Generating HTML output...[/cyan]")
        
        output_path = Path(output_path)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # Generate main HTML file
        html_file = output_path / "index.html"
        
        html_content = self._generate_html(learning_path, modules_content)
        
        with open(html_file, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        console.print(f"[green]HTML saved to: {html_file}[/green]")
    
    def _generate_html(self, learning_path: Dict, modules_content: List[Dict]) -> str:
        """Generate complete HTML document."""
        title = learning_path.get('title', 'MS Learn Content')
        summary = learning_path.get('summary', '')
        
        # Build TOC
        toc_html = self._generate_toc(modules_content)
        
        # Build content
        content_html = self._generate_content(modules_content)
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{title}</h1>
            <div class="summary">{summary}</div>
            <div class="metadata">
                <span>Duration: {learning_path.get('duration_in_minutes', 0)} minutes</span>
                <span>Modules: {learning_path.get('number_of_children', 0)}</span>
                <span>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}</span>
            </div>
        </header>
        
        <nav class="toc">
            <h2>Table of Contents</h2>
            {toc_html}
        </nav>
        
        <main>
            {content_html}
        </main>
        
        <footer>
            <p>Generated by MS Learn Downloader</p>
            <p>Original content: <a href="{learning_path.get('url', '#')}">{learning_path.get('url', '#')}</a></p>
        </footer>
    </div>
</body>
</html>"""
        return html
    
    def _generate_toc(self, modules_content: List[Dict]) -> str:
        """Generate table of contents HTML."""
        toc = ['<ol class="toc-list">']
        
        for i, module_data in enumerate(modules_content, 1):
            module = module_data['metadata']
            module_id = f"module-{i}"
            toc.append(f'<li><a href="#{module_id}">{module.get("title", "Untitled")}</a>')
            
            if module_data['content']:
                toc.append('<ol>')
                for j, unit_data in enumerate(module_data['content'], 1):
                    unit = unit_data['metadata']
                    unit_id = f"module-{i}-unit-{j}"
                    toc.append(f'<li><a href="#{unit_id}">{unit.get("title", "Untitled")}</a></li>')
                toc.append('</ol>')
            
            toc.append('</li>')
        
        toc.append('</ol>')
        return '\n'.join(toc)
    
    def _generate_content(self, modules_content: List[Dict]) -> str:
        """Generate content HTML."""
        content = []
        
        for i, module_data in enumerate(modules_content, 1):
            module = module_data['metadata']
            module_id = f"module-{i}"
            
            content.append(f'<section id="{module_id}" class="module">')
            content.append(f'<h2>Module {i}: {module.get("title", "Untitled")}</h2>')
            content.append(f'<div class="module-summary">{module.get("summary", "")}</div>')
            
            for j, unit_data in enumerate(module_data['content'], 1):
                unit = unit_data['metadata']
                unit_id = f"module-{i}-unit-{j}"
                
                content.append(f'<article id="{unit_id}" class="unit">')
                content.append(f'<h3>Unit {j}: {unit.get("title", "Untitled")}</h3>')
                content.append(unit_data.get('html', ''))
                content.append('</article>')
            
            content.append('</section>')
        
        return '\n'.join(content)
    
    def _get_css(self) -> str:
        """Get CSS styles."""
        return """
        * { box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 0;
            background: #f5f5f5;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        header {
            background: linear-gradient(135deg, #0078d4 0%, #00bcf2 100%);
            color: white;
            padding: 2rem;
        }
        header h1 { margin: 0 0 1rem 0; }
        .summary { margin: 1rem 0; font-size: 1.1rem; }
        .metadata { font-size: 0.9rem; opacity: 0.9; }
        .metadata span { margin-right: 1.5rem; }
        .toc {
            background: #f8f9fa;
            padding: 2rem;
            border-bottom: 2px solid #e0e0e0;
        }
        .toc h2 { margin-top: 0; }
        .toc-list { padding-left: 1.5rem; }
        .toc-list a { color: #0078d4; text-decoration: none; }
        .toc-list a:hover { text-decoration: underline; }
        main { padding: 2rem; }
        .module {
            margin-bottom: 3rem;
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 2rem;
        }
        .module h2 {
            color: #0078d4;
            border-left: 4px solid #0078d4;
            padding-left: 1rem;
        }
        .module-summary {
            background: #f8f9fa;
            padding: 1rem;
            margin: 1rem 0;
            border-radius: 4px;
        }
        .unit {
            margin: 2rem 0;
            padding: 1.5rem;
            background: #fafafa;
            border-radius: 4px;
        }
        .unit h3 { margin-top: 0; color: #333; }
        img { max-width: 100%; height: auto; }
        code {
            background: #f4f4f4;
            padding: 0.2rem 0.4rem;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }
        pre {
            background: #2d2d2d;
            color: #f8f8f2;
            padding: 1rem;
            border-radius: 4px;
            overflow-x: auto;
        }
        pre code {
            background: none;
            color: inherit;
            padding: 0;
        }
        footer {
            background: #333;
            color: white;
            padding: 2rem;
            text-align: center;
        }
        footer a { color: #00bcf2; }
        """


class MarkdownFormatter(BaseFormatter):
    """Format content as Markdown."""
    
    def format(self, learning_path: Dict, modules_content: List[Dict], output_path: Path):
        """Generate Markdown output."""
        console.print("[cyan]Generating Markdown output...[/cyan]")
        
        output_path = Path(output_path)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # Generate main markdown file
        md_file = output_path / "README.md"
        
        md_content = self._generate_markdown(learning_path, modules_content)
        
        with open(md_file, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        console.print(f"[green]Markdown saved to: {md_file}[/green]")
    
    def _generate_markdown(self, learning_path: Dict, modules_content: List[Dict]) -> str:
        """Generate complete Markdown document."""
        title = learning_path.get('title', 'MS Learn Content')
        summary = learning_path.get('summary', '')
        
        lines = [
            f"# {title}",
            "",
            summary,
            "",
            f"**Duration:** {learning_path.get('duration_in_minutes', 0)} minutes  ",
            f"**Modules:** {learning_path.get('number_of_children', 0)}  ",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            "",
            "---",
            "",
            "## Table of Contents",
            ""
        ]
        
        # Generate TOC
        for i, module_data in enumerate(modules_content, 1):
            module = module_data['metadata']
            lines.append(f"{i}. [{module.get('title', 'Untitled')}](#module-{i})")
            
            if module_data['content']:
                for j, unit_data in enumerate(module_data['content'], 1):
                    unit = unit_data['metadata']
                    lines.append(f"   {i}.{j}. [{unit.get('title', 'Untitled')}](#module-{i}-unit-{j})")
        
        lines.extend(["", "---", ""])
        
        # Generate content
        for i, module_data in enumerate(modules_content, 1):
            module = module_data['metadata']
            
            lines.extend([
                f"## Module {i}: {module.get('title', 'Untitled')} {{#module-{i}}}",
                "",
                module.get('summary', ''),
                ""
            ])
            
            for j, unit_data in enumerate(module_data['content'], 1):
                unit = unit_data['metadata']
                
                lines.extend([
                    f"### Unit {j}: {unit.get('title', 'Untitled')} {{#module-{i}-unit-{j}}}",
                    ""
                ])
                
                # Convert HTML to markdown if needed
                from mslearn_downloader.content_scraper import ContentScraper
                scraper = ContentScraper(None)
                unit_md = scraper.convert_to_markdown(unit_data.get('html', ''))
                lines.append(unit_md)
                lines.append("")
        
        # Footer
        lines.extend([
            "---",
            "",
            f"*Generated by MS Learn Downloader*  ",
            f"*Original content: {learning_path.get('url', '')}*"
        ])
        
        return '\n'.join(lines)
